from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from typing import List, Dict

def get_rag_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor assisting in {'English' if user_language == 'en' else 'Hebrew'}.
    Evaluate user answers, provide guidance, or answer questions based on the context provided.
    Keep responses concise, clear, and educational.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "{context}\n\n{input}")
    ])

def get_small_talk_prompt(user_language: str):
    system_message = f"""
    You are a friendly Math AI tutor engaging in small talk in {'English' if user_language == 'en' else 'Hebrew'}.
    Follow the context strictly to ask the specified small talk question or generate a retry prompt.
    Do not mention math or academic topics unless explicitly instructed.
    Keep responses short, engaging, and conversational.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "User input: {input}\nContext: {context}")
    ])

def get_personal_followup_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Acknowledge the user's hobby and ask a personalized follow-up question in a friendly, engaging way.
    Do not mention math or academic topics.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "User mentioned: {hobby}")
    ])

def get_academic_transition_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Transition from small talk to asking about the user's grade or math topic in a smooth, engaging way.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "{input}")
    ])

def get_personalized_followup_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Respond to the user's hobby or interest with a personalized, engaging follow-up question or comment.
    Do not mention math or academic topics.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "Hobby: {hobby}")
    ])

def get_humorous_reaction_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Provide a light-hearted, humorous reaction to the user's input.
    Do not mention math or academic topics in the reaction itself.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "{input}")
    ])

def get_topic_suggestion_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Generate a list of 3-5 math topics suitable for the specified grade.
    Ensure topics are relevant and age-appropriate.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        ("user", "Grade: {grade}\nContext: {context}")
    ])

def get_exercise_prompt(user_language: str) -> ChatPromptTemplate:
    system_message = f"""You are a Math AI tutor generating a new math exercise.
    
    Language: Respond in {'English' if user_language == 'en' else 'Hebrew'}
    
    Guidelines:
    - Create a unique math question for the specified grade and topic.
    - Ensure it differs from previous questions in chat history. It will be generated by LLms, so avoid repetition.
    - If there are svg images needed, describe them in the question.
    - If the question involves a diagram, include an SVG description and line ponits.
    - Include a question, solution, and one hint.
    - Format as JSON: {{ "text": {{ "question": ["question"], "solution": ["solution"], "hint": ["hint"] }}, "grade": "{{grade}}", "topic": "{{topic}}" }}
    - For Hebrew, use RTL for text, LTR for math expressions.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "Generate a new exercise for grade {grade} on topic {topic}.")
    ])

def get_guiding_question_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Generate a guiding question to help the user think through a math problem based on their incorrect answer.
    Keep it concise and encouraging.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "Question: {question}\nUser's answer: {answer}\nContext: {context}")
    ])

def get_solution_explanation_prompt(user_language: str):
    system_message = f"""
    You are a Math AI tutor in {'English' if user_language == 'en' else 'Hebrew'}.
    Provide a clear, step-by-step explanation of the solution to the math problem.
    Ensure the explanation is educational and easy to understand.
    """
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "Question: {question}\nSolution: {solution}")
    ])

def generate_humor_response(llm, user_language: str, user_input: str) -> str:
    try:
        humor_prompt = ChatPromptTemplate.from_messages([
            ("system", f"Respond with a light-hearted, humorous comment in {'English' if user_language == 'en' else 'Hebrew'} based on the user's input. Do not mention math or academic topics."),
            ("user", "User input: {input}")
        ])
        humor_chain = humor_prompt | llm
        response = humor_chain.invoke({"input": user_input})
        return response.content.strip()
    except Exception as e:
        print(f"Error generating humor response: {e}")
        return "Haha, nice one!" if user_language == "en" else "חהחה, יפה!"

def generate_guiding_question(llm, user_language: str, chat_history: List, question: str, answer: str, context: str) -> str:
    try:
        guiding_prompt = get_guiding_question_prompt(user_language)
        guiding_chain = guiding_prompt | llm
        response = guiding_chain.invoke({
            "chat_history": chat_history[-3:],
            "question": question,
            "answer": answer,
            "context": context
        })
        return response.content.strip()
    except Exception as e:
        print(f"Error generating guiding question: {e}")
        return "Can you explain your thinking?" if user_language == "en" else "האם תוכל להסביר את החשיבה שלך?"

def generate_solution_explanation(llm, user_language: str, chat_history: List, question: str, solution: str) -> str:
    try:
        solution_prompt = get_solution_explanation_prompt(user_language)
        solution_chain = solution_prompt | llm
        response = solution_chain.invoke({
            "chat_history": chat_history[-3:],
            "question": question,
            "solution": solution
        })
        return response.content.strip()
    except Exception as e:
        print(f"Error generating solution explanation: {e}")
        return f"Solution: {solution}" if user_language == "en" else f"פתרון: {solution}"

def generate_lesson_summary(llm, user_language: str, chat_history: List, diagnostic: Dict) -> str:
    try:
        summary_prompt = ChatPromptTemplate.from_messages([
            ("system", f"Summarize the lesson in {'English' if user_language == 'en' else 'Hebrew'}, highlighting key topics and user progress."),
            MessagesPlaceholder(variable_name="chat_history"),
            ("user", "Diagnostic: {diagnostic}")
        ])
        summary_chain = summary_prompt | llm
        response = summary_chain.invoke({
            "chat_history": chat_history[-5:],
            "diagnostic": str(diagnostic)
        })
        return response.content.strip()
    except Exception as e:
        print(f"Error generating lesson summary: {e}")
        return "Great job today!" if user_language == "en" else "עבודה נהדרת היום!"

def is_likely_hebrew(text: str) -> bool:
    try:
        return any(1424 <= ord(c) <= 1514 for c in text)
    except Exception:
        return False

def describe_svg_content(llm, svg_content: str) -> str:
    try:
        svg_prompt = ChatPromptTemplate.from_messages([
            ("system", "Describe the content of the provided SVG in English, focusing on elements relevant to the math problem."),
            ("user", "SVG content: {svg_content}")
        ])
        svg_chain = svg_prompt | llm
        response = svg_chain.invoke({"svg_content": svg_content})
        return response.content.strip()
    except Exception as e:
        print(f"Error describing SVG content: {e}")
        return "SVG description unavailable."

def detect_intent(llm, user_language: str, chat_history: List, question: str, user_input: str) -> str:
    try:
        intent_prompt = ChatPromptTemplate.from_messages([
            ("system", f"Determine the user's intent in {'English' if user_language == 'en' else 'Hebrew'}. Options: 'answer_attempt', 'hint_request', 'solution_request', 'new_exercise_request'."),
            MessagesPlaceholder(variable_name="chat_history"),
            ("user", "Current question: {question}\nUser input: {user_input}\n\nIdentify the intent.")
        ])
        intent_chain = intent_prompt | llm
        response = intent_chain.invoke({
            "chat_history": chat_history[-3:],
            "question": question,
            "user_input": user_input
        })
        return response.content.strip()
    except Exception as e:
        print(f"Error detecting intent: {e}")
        return "answer_attempt"

def translate_text_to_english(llm, text: str) -> str:
    try:
        if is_likely_hebrew(text):
            translate_prompt = ChatPromptTemplate.from_messages([
                ("system", "Translate the provided Hebrew text to English, preserving mathematical expressions."),
                ("user", "Text: {text}")
            ])
            translate_chain = translate_prompt | llm
            response = translate_chain.invoke({"text": text})
            return response.content.strip()
        return text
    except Exception as e:
        print(f"Error translating text: {e}")
        return text